### ISSUE TITLE
[QUESTION] - Material (.mtl) for my Object

### ISSUE THREAD

**Issue by Ahmadre** [hemanthrajv/flutter_3d_obj#15]
Is it possible to render my materials to my object? Or how do I combine them to be rendered in this plugin?

**Comment by hemanthrajv** [comment]
The plugin doesn't support .mtl for now. Only renders your objects.

I couldn't find much time to add the support, I'll try but not sure if I'll do them any sooner. 

Feel free to add one if you could and place a PR. I'll be more than happy to accept your PR.

**Comment by Ahmadre** [comment]
I can help you @hemanthrajv . What do we need to do in a short? iterate through all faces and add the relevant material?

**Comment by Ahmadre** [comment]
Nevermind I use https://pub.dev/packages/flutter_unity_widget now in combination with Blender and it's very fast.
