### ISSUE TITLE
Build Failed: Update Version Environment

### ISSUE THREAD

**Issue by PramUkesh** [hemanthrajv/flutter_3d_obj#5]
The current Dart SDK version is 2.1.0-dev.1.0.flutter-ccb16f7282.

Because appdepends on flutter_3d_obj any which requires SDK version >=1.8.0 <2.0.0, version solving failed.
pub get failed (1)

**Comment by hemanthrajv** [comment]
Closing with respect to this [https://github.com/hemanthrajv/flutter_3d_obj/commit/b9815356f5e8e5d8163b3ec7a3c692b140e7f991](commit)
