### ISSUE TITLE
Not working with other blender models

### ISSUE THREAD

**Issue by mcprakash** [hemanthrajv/flutter_3d_obj#8]
Hi @hemanthrajv 
 The example works out of the box if I update the gradle version to latest. 

 I am facing issues with loading a different model. I tried a couple of models and am getting the error

 `E/flutter (31925): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: Unable to load asset: assets/BodyMesh.obj`

 Thank you again for sharing your awesome work. 

Best
Chandra

**Comment by mcprakash** [comment]
PFA the file I am trying to use. Hope this helps. Please do let me know if there is some specific format that must be used to export the .obj file. 

Thanks again. 

[zsmsxsymf1-BodyMesh.zip](https://github.com/hemanthrajv/flutter_3d_obj/files/3124198/zsmsxsymf1-BodyMesh.zip)

**Comment by hemanthrajdc** [comment]
Hi, thanks for writing to me. The library merely renders 3D object from `.obj` file.

Your body mesh does work perfect without any issues.

Here is the screenshot of your model
![screenshot](https://user-images.githubusercontent.com/49126054/56853852-e57a3a80-694a-11e9-9d36-1d5e43052a36.png)

**Comment by hemanthrajv** [comment]
Hi, thanks for writing to me. The library merely renders 3D object from `.obj` file.

Your body mesh does work perfect without any issues.

Here is the screenshot of your model
![screenshot](https://user-images.githubusercontent.com/49126054/56853852-e57a3a80-694a-11e9-9d36-1d5e43052a36.png)

Things you can check:

- See if you've added the `.obj` file to assets correctly
- Check if assets are specified properly in your `pubspec.yaml`
- Ensure the asset name is correctly give to the `Object3D` class

Hope this helps!

**Comment by hemanthrajv** [comment]
Closing the issue as it is not related to the plugin.

**Comment by hemanthrajv** [comment]
Closing the issue as it is not plugin related.

Feel free to get back if the above methods did not help!

**Comment by mcprakash** [comment]
Hi @hemanthrajv 
 Can you let me know the platform you are using to test this ? If using an emulator, please let me know if tihs works on a real device. 
 
 The code compiles fine and I am getting run time error as mentioned above. Here is the exact info I get from my terminal. 

 I think this may be a run time issue related to my mobile. I am uisng Samsung Galaxy S8. 
 
 Let me know if you can help me with this. 

Best
Chandra
<-------------------------------------------------------------------------------------------------------------------------------->
 ✝  ~/Downloads/flutter_3d_obj-master/example  flutter run
Launching lib/main.dart on SM G955U1 in debug mode...
Initializing gradle...                                              0.9s
Resolving dependencies...                                           1.5s
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                         1.4s
Built build/app/outputs/apk/debug/app-debug.apk.
D/SurfaceView(31925): destroy() Surface(name=SurfaceView - com.yourcompany.example/com.yourcompany.example.MainActivity@c2eb9d9@0[31925])/@0xc24da7f io.flutter.view.FlutterView{c2eb9
d9 VFE...... .F....ID 0,0-1080,2094}
I/Choreographer(31925): Skipped 101 frames!  The application may be doing too much work on its main thread.
D/ViewRootImpl@5846f23[MainActivity](31925): Relayout returned: old=[0,0][1080,2220] new=[0,0][1080,2220] result=0x3 surface={valid=true 498523344896} changed=false
D/vndksupport(31925): Loading /vendor/lib64/hw/android.hardware.graphics.mapper@2.0-impl.so from current namespace instead of sphal namespace.
D/vndksupport(31925): Loading /vendor/lib64/hw/gralloc.msm8998.so from current namespace instead of sphal namespace.
E/flutter (31925): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: Unable to load asset: assets/BodyMesh.obj
E/flutter (31925): #0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:221:7)
E/flutter (31925): <asynchronous suspension>                            
E/flutter (31925): #1      AssetBundle.loadString (package:flutter/src/services/asset_bundle.dart:67:33)
E/flutter (31925): <asynchronous suspension>                            
E/flutter (31925): #2      CachingAssetBundle.loadString.<anonymous closure> (package:flutter/src/services/asset_bundle.dart:162:56)
E/flutter (31925): #3      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:281:23)
E/flutter (31925): #4      CachingAssetBundle.loadString (package:flutter/src/services/asset_bundle.dart:162:27)
E/flutter (31925): #5      _Object3DState.initState (package:flutter_3d_obj/flutter_3d_obj.dart:42:18)
E/flutter (31925): #6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3846:58)
E/flutter (31925): #7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
E/flutter (31925): #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
E/flutter (31925): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
E/flutter (31925): #10     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
E/flutter (31925): #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
E/flutter (31925): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
E/flutter (31925): #13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
E/flutter (31925): #14     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
E/flutter (31925): #15     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
E/flutter (31925): #16     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
E/flutter (31925): #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
E/flutter (31925): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
E/flutter (31925): #19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
E/flutter (31925): #20     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
E/flutter (31925): #21     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
E/flutter (31925): #22     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
E/flutter (31925): #23     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:4063:11)
E/flutter (31925): #24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
E/flutter (31925): #25     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4982:32)
E/flutter (31925): #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
E/flutter (31925): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
E/flutter (31925): #28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
E/flutter (31925): #29     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
E/flutter (31925): #30     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
E/flutter (31925): #31     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
E/flutter (31925): #32     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
E/flutter (31925): #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
E/flutter (31925): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
E/flutter (31925): #35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
E/flutter (31925): #36     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
E/flutter (31925): #37     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
E/flutter (31925): #38     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
E/flutter (31925): #39     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
E/flutter (31925): #40     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
E/flutter (31925): #41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
E/flutter (31925): #42     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
E/flutter (31925): #43     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
E/flutter (31925): #44     StatefulElement._firstBuild (package:flutter/src/widget
I/OpenGLRenderer(31925): Davey! duration=1743ms; Flags=1, IntendedVsync=896177863416259, Vsync=896179546749525, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=896179547511988, AnimationStart=896179547719592, PerformTraversalsStart=896179547814748, DrawStart=896179572268550, SyncQueued=896179577274956, SyncStart=896179577383863, IssueDrawCommandsStart=896179577668967, SwapBuffers=896179603368810, FrameCompleted=896179607030946, DequeueBufferDuration=6627000, QueueBufferDuration=1852000, 
D/ViewRootImpl@5846f23[MainActivity](31925): MSG_RESIZED_REPORT: frame=Rect(0, 0 - 1080, 2220) ci=Rect(0, 63 - 0, 126) vi=Rect(0, 63 - 0, 126) or=1
Syncing files to device SM G955U1...                             1,956ms

🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
An Observatory debugger and profiler on SM G955U1 is available at: http://127.0.0.1:39453/
For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
Application finished.
 ✝  ~/Downloads/flutter_3d_obj-master/example  
<-------------------------------------------------------------------------------------------------------------------------------->

**Comment by mcprakash** [comment]
![Screenshot from 2019-04-28 10-51-13](https://user-images.githubusercontent.com/8052668/56857714-9ca2a000-69a3-11e9-8746-4e64dd156cfc.png)
![Screenshot from 2019-04-28 10-50-54](https://user-images.githubusercontent.com/8052668/56857716-9e6c6380-69a3-11e9-9d41-983af7fc8bc9.png)

![Screenshot_20190428-082103](https://user-images.githubusercontent.com/8052668/56857757-e55a5900-69a3-11e9-80eb-b76f7d11108f.jpg)
![Screenshot_20190428-082237](https://user-images.githubusercontent.com/8052668/56857759-e55a5900-69a3-11e9-8d3a-770815fcfa6e.jpg)

**Comment by mcprakash** [comment]
Hi @hemanthrajv 
  I renamed the file to `abodymesh.obj` and it works ok now. Maybe something to do with file name. 

Best
Chandra

**Comment by mcprakash** [comment]
![Screenshot_20190428-083113](https://user-images.githubusercontent.com/8052668/56857878-0e2f1e00-69a5-11e9-88dd-1aae69bfcefe.jpg)

**Comment by AbdullahAlAsad** [comment]
How can I add texture to this  models ?
Also is there a way to pinch zoom ?
